spring:
  application:
    name: discodeit
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    root: info

discodeit:
  repository:
    type: jpa
    file-directory: .discodeit
  storage:
    type: local
    local:
      root-path: uploads