spring:
  application:
    name: discodeit
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    root: info
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

discodeit:
  repository:
    type: jpa
    file-directory: .discodeit
  storage:
    type: local
    local:
      root-path: uploads