server:
  port: 80

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/discodeit}
    username: ${DB_USERNAME:discodeit_user}
    password: ${DB_PASSWORD:discodeit1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgres

logging:
  level:
    root: info

    org.springframework: warn
    com.zaxxer.hikari: warn

    org.hibernate.SQL: off
    com.sprint.mission.discodeit: info